import { tsGen, tsStatements, tsExpression } from '../src';
import { factory } from 'typescript';

describe('blah', () => {
  it('works', () => {
    const aName = "a"
    const e = factory.createFunctionDeclaration(
      [],
      [],
      undefined,
      'test',
      [],
      [],
      factory.createTypeReferenceNode('string'),
      factory.createBlock(tsStatements`
      const ${aName} = "test"
      ${tsExpression`return ${aName}`}
      `)
    );
    expect(
      tsGen`// generated by moi
${tsGen`const a = ${tsExpression`'test'`} // inline comments`}

// test
${e}

const b = 1`
    ).toEqual(`// generated by moi
const a = "test"; // inline comments

// test
function test(): string {
  const a = "test";
  return a;
}

const b = 1;
`);
  });
});
